schedules:
- cron: "0 2 * * *"
  displayName: Daily morning build
  branches:
    include:
    - main

variables: 
  - group: variables
    
steps:
  - bash: |
      sqlcmd -U $(sqlUsername) \
        -P $(sqlPassword) \
        -d "master" \
        -S $(sqlHostname) \
        -C \
        -l 30 \
        -Q "EXECUTE dbo.DatabaseBackup @Databases='USER_DATABASES',@Directory='/backup/',@BackupType='FULL',@Verify='Y',@CleanupTime=168,@CheckSum='Y',@NumberOfFiles=14"