schedules:
- cron: "0 2 * * *"
  displayName: Daily morning build
  branches:
    include:
    - main

variables: 
  - group: variables
    
steps:
  - bash: |
      sqlcmd -U "$($sqlUsername)" \
        -P "$($sqlPassword)" \
        -d "master" \
        -S "$($sqlHostname)" \
        -C \
        -i "../sql/backup.sql"