pool: 
  name: 'Default'

variables:
  - template: ./deploy/variables/variables.yml
  - group: variables

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)
stages:
  - template: ./deploy/stages/app_build_stage.yml
    parameters:
      projectName: ${{ variables.projectName }}
  
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - template: ./deploy/stages/app_deploy_stage.yml
      parameters:
        projectName: ${{ variables.projectName }}