schedules:
- cron: "0 2 * * *"
  displayName: Daily morning build
  branches:
    include:
    - main
  always: "true"

trigger: none

pool: 
  name: "Default"

variables: 
  - group: variables
    
steps:
  - checkout: none
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        Install-Module -Name SqlServer -Force
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        Invoke-SqlCmd -ServerInstance $(sqlHostname) -Database master -Username $(sqlUsername) -Password $(sqlPassword) -Query "EXECUTE dbo.DatabaseBackup @Databases='USER_DATABASES',@Directory='/backup/',@BackupType='FULL',@Verify='Y',@CleanupTime=168,@CheckSum='Y',@NumberOfFiles=14"
    