schedules:
- cron: "0 2 * * *"
  displayName: Daily morning build
  branches:
    include:
    - main

variables: 
  - group: variables
    
pool: 
  name: "Default"
    
steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        Install-Module -Name SqlServer -Force
    enabled: "false"
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        Invoke-SqlCmd -ServerInstance $(sqlHostname) -Database master -Username $(sqlUsername) -Password $(sqlPassword) -Query "select 1 1"
    enabled: "false"
  - bash: |
      sqlcmd -U $(sqlUsername) \
        -P $(sqlPassword) \
        -d "master" \
        -S $(sqlHostname) \
        -C \
        -l 30 \
        -Q "EXECUTE dbo.DatabaseBackup @Databases='USER_DATABASES',@Directory='/backup/',@BackupType='FULL',@Verify='Y',@CleanupTime=168,@CheckSum='Y',@NumberOfFiles=14"