# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Laptop'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet tool restore'
  inputs: 
   command: 'custom'
   custom: 'tool'
   arguments: 'restore'
   
- task: Kubernetes@1
  displayName: 'Test K3s connection'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Local K3S'
    command: 'get'
    arguments: 'nodes'
    outputFormat: none

- task: Docker@2
  displayName: 'Docker login'
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'

- script: $(Agent.BuildDirectory)/tools/tye deploy tye.production.yaml --verbosity debug 
  workingDirectory: 'src'
  displayName: 'Build and deploy'

- task: Kubernetes@1
  displayName: 'rollout identity-api'
  inputs:
   connectionType: Kubernetes Service Connection
   kubernetesServiceEndpoint: 'Local K3S'
   namespace: 'default'
   command: rollout
   arguments: restart deployment identity-api

- task: Kubernetes@1
  displayName: 'rollout smoking-api'
  inputs:
   connectionType: Kubernetes Service Connection
   kubernetesServiceEndpoint: 'Local K3S'
   namespace: 'default'
   command: rollout
   arguments: restart deployment smoking-api

- task: Kubernetes@1
  displayName: 'rollout webblazor'
  inputs:
   connectionType: Kubernetes Service Connection
   kubernetesServiceEndpoint: 'Local K3S'
   namespace: 'default'
   command: rollout
   arguments: restart deployment webblazor
   
- task: Kubernetes@1
  displayName: 'rollout webstatus'
  inputs:
   connectionType: Kubernetes Service Connection
   kubernetesServiceEndpoint: 'Local K3S'
   namespace: 'default'
   command: rollout
   arguments: restart deployment webstatus

- task: KubernetesManifest@0
  displayName: 'patch ingress'
  inputs:
   action: patch
   kind: ingress
   name: ingress
   patch: '{"metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-production"}},"spec":{"tls":[{"hosts":["app.itadams.co.uk"],"secretName":"webblazor-production-tls"},{"hosts":["identity.itadams.co.uk"],"secretName":"identity-api-production-tls"},{"hosts":["status.itadams.co.uk"],"secretName":"webstatus-production-tls"}]}}'
   kubernetesServiceConnection: 'Local K3S'