pool: 
  vmImage: 'ubuntu-latest'

variables:
  - template: ./deploy/variables/common-variables.yml

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)
stages:
  - template: ./deploy/stages/docker_build_and_push_stage.yml
    parameters:
      projectName: Nexus