# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Laptop'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet tool restore'
  inputs: 
   command: 'custom'
   custom: 'tool'
   arguments: 'restore'
   
- task: Kubernetes@1
  displayName: 'Test K3s connection'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Local K3S'
    command: 'get'
    arguments: 'nodes'
    outputFormat: none

- task: Docker@2
  displayName: 'Docker login'
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'

- script: $(Agent.BuildDirectory)/tools/tye undeploy tye.production.yaml --verbosity debug 
  workingDirectory: 'src'
  displayName: 'Undeploy'

- script: $(Agent.BuildDirectory)/tools/tye deploy tye.production.yaml --verbosity debug 
  workingDirectory: 'src'
  displayName: 'Build and deploy'

- task: KubernetesManifest@0
  displayName: 'patch ingress'
  inputs:
   action: patch
   kind: ingress
   name: ingress
   patch: "$(cat ingress-ssl-patch.yaml)"
   kubernetesServiceConnection: 'Local K3S'