schedules:
- cron: "0 2 * * *"
  displayName: Daily morning build
  branches:
    include:
    - main

variables: 
  - group: variables
    
steps:
  - bash: |
      mssql-cli --username "$($sqlUsername)" \
        --password "$($sqlPassword)" \
        --database "master" \
        --server "$($sqlHostname)" \
        --trust-server-certificate \
        --input_file "../sql/backup.sql"