version: '3.4'

services:
  nexus.todo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5300:80"

  nexus.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ReverseProxy__Clusters__todo__Destinations__primary__Address=http://${EXTERNAL_DNS_NAME_OR_IP}:5300
    ports:
      - "5100:80"
     

  nexus.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApiGatewayUrl=http://${EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "5200:80"


  nexus.edge.router:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
