version: '3.4'

name: nexus

services:   
  zipkin.storage:
    image: ghcr.io/openzipkin/zipkin-mysql:${TAG:-latest}

  zipkin:
    image: ghcr.io/openzipkin/zipkin:${TAG:-latest}
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin.storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin.storage
    ports:
      - 9411:9411
    
  zipkin.dependencies:
    image: ghcr.io/openzipkin/zipkin-dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin.storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin.storage
    
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - docker/seq/data:/data

  nexus.todo.api:
    image: ${DOCKER_REGISTRY:-tjackadams}/nexus.todo.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Todo.Api/Dockerfile
    pull_policy: always
    depends_on:
      - seq

  nexus.weighttracker.api:
    image: ${DOCKER_REGISTRY:-tjackadams}/nexus.weighttracker.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.WeightTracker.Api/Dockerfile
    pull_policy: always
    depends_on:
      - seq
      - zipkin

  nexus.gateway:
    image: ${DOCKER_REGISTRY:-tjackadams}/nexus.gateway:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Gateway/Dockerfile
    pull_policy: always
    depends_on:
      - seq
      - nexus.todo.api
      - nexus.weighttracker.api

  nexus.portal:
    image: ${DOCKER_REGISTRY:-tjackadams}/nexus.portal:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Portal/Dockerfile
    pull_policy: always
    depends_on:
      - seq
      - nexus.gateway


