version: '3.4'

services:
  nexus.todo.api:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5300:80"

  nexus.gateway:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5100:80"
     
  nexus.portal:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - LettuceEncrypt__AcceptTermsOfService=true
      - LettuceEncrypt__DomainNames__0=${DomainName}
      - LettuceEncrypt__EmailAddress=${EmailAddress}
      - PfxPassword=${PfxPassword}
    ports:
      - "5200:443"
    volumes: 
      - /volume1/docker/data/nexus.portal:/app/data:rw