version: '3.4'

services:
  nexus.todo.api:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Nexus=${NexusDatabase}Application Name=nexus.todo.api
    ports:
      - "5300:80"

  nexus.weighttracker.api:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Nexus=${NexusDatabase}Application Name=nexus.weighttracker.api
    ports:
      - "5301:80"

  nexus.gateway:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Clusters__nexustodoapi__Destinations__primary__Address=http://nexus.todo.api
      - Clusters__nexusweighttrackerapi__Destinations__primary__Address=http://nexus.weighttracker.api
    ports:
      - "5100:80"
     
  nexus.portal:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - LettuceEncrypt__AcceptTermsOfService=true
      - LettuceEncrypt__DomainNames__0=${DomainName}
      - LettuceEncrypt__EmailAddress=${EmailAddress}
      - PfxPassword=${PfxPassword}
      - AzureAD__ClientSecret=${ClientSecret}
      - Settings__ApiGatewayUri=http://nexus.gateway
    ports:
      - "5200:443"
    volumes: 
      - /volume1/docker/data/nexus.portal:/app/data:rw