version: '3.4'

services:
  nexus.todo.api:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5300:80"

  nexus.gateway:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5100:80"
     
  nexus.portal:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5200:80"

  nexus.edge.router:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ReverseProxy__Clusters__cluster1__Destinations__destination1__Address=http://nexus.portal
    ports:
      - "6000:80"
      - "6001:443"