version: '3.4'

services:    
  nexus.todo.api:
    image: ${DOCKER_REGISTRY:-tjackadams}nexus.todo.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Todo.Api/Dockerfile

  nexus.gateway:
    image: ${DOCKER_REGISTRY:-tjackadams}nexus.gateway:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Gateway/Dockerfile
    depends_on:
      - nexus.todo.api

  nexus.portal:
    image: ${DOCKER_REGISTRY:-tjackadams}nexus.portal:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Portal/Dockerfile
    depends_on:
      - nexus.gateway

  nexus.edge.router:
    image: ${DOCKER_REGISTRY:-tjackadams}nexus.edge.router:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Edge.Router/Dockerfile

