version: '3.4'

services:    
  nexus.todo.api:
    image: ${DOCKER_REGISTRY-}nexustodoapi
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Todo.Api/Dockerfile

  nexus.gateway:
    image: ${DOCKER_REGISTRY-}nexusgateway
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Gateway/Dockerfile
    depends_on:
      - nexus.todo.api

  nexus.portal:
    image: ${DOCKER_REGISTRY-}nexusportal
    build:
      context: .
      dockerfile: Nexus.Hub/Nexus.Portal/Dockerfile
    depends_on:
      - nexus.gateway

