CREATE TABLE [Todo].[Todos]
(
	[TodoId] INT NOT NULL IDENTITY(1,1),
    [Title] NCHAR(10) NOT NULL, 
    [CreatedTime] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), 
    CONSTRAINT PK_Todos PRIMARY KEY ([TodoId] ASC)
)
