steps:
  - task: EnvTransform@0
    inputs:
      inputType: 'inline'
      content: |
        DomainName="$(domainName)"
        EmailAddress="$(emailAddress)"
        PfxPassword="$(pfxPassword)"
        ClientSecret="$(clientSecret)"
        NexusDatabase="$(connectionString)"
      outputFile: 'prod.env'