parameters:
  - name: dacpacFile
    type: string
  - name: sqlServerName
  - name: sqlDatabase
  - name: sqlUsername
  - name: sqlPassword

steps:
  - task: SqlDacpacDeploymentOnMachineGroup@0
    displayName: 'Deploy ${{ parameters.sqlDatabase }} on ${{ parameters.sqlServerName }}'
    inputs:
      TaskType: 'dacpac'
      DacpacFile: ${{ parameters.dacpacFile }}
      TargetMethod: 'server'
      ServerName: ${{ parameters.sqlServerName }}
      DatabaseName: ${{ parameters.sqlDatabase }}
      AuthScheme: 'sqlServerAuthentication'
      SqlUsername: ${{ parameters.sqlUsername }}
      SqlPassword: ${{ parameters.sqlPassword }}