parameters:
  - name: dacpacFile
    type: string
  - name: connectionString
    type: string
  - name: blockOnPossibleDataLoss
    type: string
    default: 'false'
  - name: generateSmartDefaults
    type: string
    default: 'true'

steps:
  - script: |
      /opt/sqlpackage/sqlpackage /a:Publish /p:BlockOnPossibleDataLoss=${{ parameters.blockOnPossibleDataLoss }} /p:GenerateSmartDefaults=${{ parameters.generateSmartDefaults }} /tcs:"${{ parameters.connectionString }}" /sf:"${{ parameters.dacpacPath }}" 