parameters:
  - name: bundleLocation
    type: string
  - name: connectionString
    type: string

steps:
  - script: |
      chmod +x 
    workingDirectory: ${{ parameters.bundleLocation }}
  - script: |
      /opt/sqlpackage/sqlpackage /a:Publish /p:BlockOnPossibleDataLoss=${{ parameters.blockOnPossibleDataLoss }} /p:GenerateSmartDefaults=${{ parameters.generateSmartDefaults }} /tcs:"${{ parameters.connectionString }}" /sf:"${{ parameters.dacpacFile }}" 
    displayName: Deploy Dacpac