parameters:
  - name: dockerFilePath
  - name: projectName
    
steps:     
  - task: DockerCompose@0
    displayName: Build Docker Image
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      dockerComposeFile: 'docker-compose.yml'
      additionalDockerComposeFiles: 'docker-compose.prod.yml'
      action: Run a Docker Compose command
      additionalImageTags: $(Build.BuildId)
      dockerComposeCommand: build ${{ lower(parameters.projectName) }} --build-arg TF_BUILD=$($TF_BUILD)
