parameters:
  - name: dockerFilePath
  - name: projectName
    
steps:
  - task: DockerCompose@0
    displayName: Push Docker Image
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      dockerComposeFile: 'docker-compose.yml'
      additionalDockerComposeFiles: 'docker-compose.prod.yml'
      action: 'Push services'   
      arguments: '${{ lower(parameters.projectName) }}'
      additionalImageTags: $(Build.BuildId)