parameters:
  - name: dockerFilePath
  - name: projectName
    
steps:
  - task: Docker@2
    displayName: Push Docker Image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'tjackadams/nexus'
      command: 'push'     
      tags: '$(Build.BuildNumber)'