parameters:
  - name: dockerFilePath
  - name: projectName
    
steps:
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'tjackadams/nexus'
      command: 'build'
      Dockerfile: ${{ parameters.dockerFilePath }}
      buildContext: '.'
      arguments: '--build-arg $(TF_BUILD)'    
      tags: '$(Build.BuildNumber)' 
     