parameters:
  - name: dockerFilePath
  - name: projectName
    
steps:
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      Dockerfile: ${{ parameters.dockerFilePath }}
      arguments: '--build-arg TF_BUILD=$TF_BUILD'
      command: 'build'
    env:
      TF_BUILD: $(TF_BUILD)
     