parameters:
  - name: dockerFilePath
  - name: projectName
    
steps:
  - script: |
      docker buildx create --name multibuilder
    displayName: Create Docker Multi-Builder
  - script: |
      docker buildx inspect multibuilder --bootstrap
    displayName: Bootstrap Docker Multi-Builder
  - script: |
      docker buildx use multibuilder
    displayName: Use Docker Multi-Builder
  - script: |
      docker buildx build -f "${{ parameters.dockerFilePath }}" --platform linux/amd64,linux/arm64 -t ${{ lower(parameters.projectName) }} .
    displayName: Build Docker Image ${{ replace(parameters.projectName, '.','_') }}
    env:
      TF_BUILD: $(TF_BUILD)
     