parameters:
  - name: context
    type: string
  - name: connectionString
    type: string

steps:     
  - bash: |
      contexts=$(docker context ls --format='{{.Name}}')
      if grep -q "${{ parameters.context }}" <<< "$contexts"; then
        echo "context ${{ parameters.context }} already exists"
      else
        docker context create ${{ parameters.context }} --docker "${{ parameters.connectionString }}"
      fi
    displayName: 'Creating Docker Context: ${{ parameters.context }}'