parameters:
  - name: dockerFilePath
  - name: projectName
    
steps:
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'tjackadams'
      command: 'build'
      Dockerfile: ${{ parameters.dockerFilePath }}
      buildContext: '.'
      arguments: '--build-arg TF_BUILD=$TF_BUILD'    
      tags: '$(Build.BuildNumber)' 
    env:
      TF_BUILD: $(TF_BUILD)
     