parameters:
    - name: projectPath
      default: ''
    - name: startUpProjectPath
      default: ''
    - name: dropLocation
      default: ''
    - name: projectName
      default: ''

steps:
  - script: |
        dotnet ef migrations bundle --project ${{ parameters.projectPath }} \
          --startup-project ${{ parameters.startUpProjectPath }} \
          --output ${{ parameters.dropLocation }}/${{ parameters.projectName }}/bundle \
          --configuration Release \
          --verbose
    displayName: 'Build EF Migration Bundle'