parameters:
  - name: projectName
    type: string

jobs:
  - job: build_publish_${{ parameters.projectName }}
    variables:
      - name: projectName
        value: ${{replace(parameters.projectName,'_','.')}}
      - name: srcFilePath
        value: "Nexus.Hub"
      - name: projectPath
        value: "$(Build.SourcesDirectory)/${{ variables.srcFilePath }}/${{ variables.projectName }}"
      - name: dropLocation
        value: "drop/${{ parameters.projectName }}"
    steps:
      - template: ../tasks/dotnet_sdk_task.yml
      - template: ../tasks/dotnet_tools_restore_task.yml
      - template: ../tasks/ef_migration_bundle__build_task.yml
        parameters:
          projectPath: ${{ variables.projectPath }}
          startUpProjectPath: ${{ variables.projectPath }}
          dropLocation: ${{variables.dropLocation }}
          projectName: ${{ variables.projectName }}

      - template: ../tasks/ado_publish_pipeline_task.yml
        parameters:
          artifactName: ${{ parameters.projectName }}
          targetPath: ${{ variables.dropLocation }}
