parameters:
  - name: projectName
    type: string
  - name: environmentName
    type: string
    default: 'production'

jobs:
- deployment: '${{ parameters.projectName }}_${{ parameters.environmentName }}_SQL'
  environment: ${{ parameters.environmentName }}
  variables:
    - name: bundleLocation
      value: $(Pipeline.Workspace)/${{ parameters.projectName }}
    - name: connectionString
      value: 'Server=$(sqlHostname);Database=$(sqlDatabase);User Id=$(sqlUsername);Password=$(sqlPassword);'

  strategy: 
   runOnce:
     deploy:
       steps:
         - template: ../tasks/ado_download_pipeline_task.yml
         - template: ../tasks/ef_migration_bundle_deploy_task.yml
           parameters:
            bundleLocation: ${{ variables.bundleLocation }}
            connectionString: ${{ variables.connectionString }}