parameters:
  - name: projectName
    type: string

jobs:
  - job: Build_${{ replace(parameters.projectName, '.','_') }}
    steps:
     - template: ../tasks/docker_context_cli_task.yml
       parameters:
        context: $(buildContext)
     - template: ../tasks/docker_login_cli_task.yml
     - template: ../tasks/docker_build_cli_task.yml
     - template: ../tasks/docker_push_cli_task.yml