parameters:
  - name: dockerFilePath
    type: string
  - name: projectName

jobs:
  - job: Build_${{ parameters.projectName }}
    steps:
     - template: ../tasks/docker_build_cli_task.yml
       parameters:
        dockerFilePath: ${{ parameters.dockerFilePath }}