parameters:
  - name: projectName
    type: string
  - name: environmentName
    type: string
    default: 'production'

jobs:
  - deployment: '${{ parameters.projectName }}_${{ parameters.environmentName }}'
    environment: ${{ parameters.environmentName }}
    pool: 
      name: ${{ variables.deployPool }}
    strategy: 
      runOnce:
        deploy:
          steps:
            - template: ../tasks/docker_context_create_cli_task.yml
              parameters:
                context: $(deployContext)
                connectionString: $(dockerConnectionString)
            - template: ../tasks/docker_context_cli_task.yml
              parameters:
                context: $(deployContext)
            - template: ../tasks/ado_create_env_task.yml
            - template: ../tasks/docker_up_cli_task.yml
  