parameters:
  - name: dockerFilePath
    type: string
  - name: projectName

jobs:
  - job: Build_${{ replace(parameters.projectName, '.','_') }}
    steps:
     - template: ../tasks/docker_build_cli_task.yml
       parameters:
        dockerFilePath: ${{ parameters.dockerFilePath }}
        projectName: ${{ parameters.projectName }}