parameters:
  - name: projectName
    type: string
  - name: environmentName
    type: string
    default: 'production'

jobs:
- deployment: '${{ parameters.projectName }}_${{ parameters.environmentName }}_SQL'
  environment: ${{ parameters.environmentName }}
  variables:
    - name: dacpacFile
      value: $(Pipeline.Workspace)\${{ parameters.projectName }}.Database.dacpac
    - name: connectionString
      value: 'Server=$(sqlServerName);Database=$(sqlDatabase);User Id=$(sqlUsername);Password=$(sqlPassword);'

  strategy: 
   runOnce:
     deploy:
       steps:
         - template: ../tasks/ado_download_pipeline_task.yml
         - template: ../tasks/dacpac_deploy_task.yml
           parameters:
            dacpacFile: ${{ variables.dacpacFile }}
            connectionString: ${{ variables.connectionString }}