parameters:
  - name: projectName
    type: string
    
stages:
  - stage: build_${{ parameters.projectName }}
    jobs:
      - template: ../jobs/docker_build_and_push_job.yml
        parameters:
          projectName: ${{ parameters.projectName }}
      - template: ../jobs/db_build_and_publish_job.yml
        parameters:
          projectName: ${{ parameters.projectName }}.Database
          
    