parameters:
  - name: projectName
    type: string
  - name: dbProjects
    type: object
    default: ['Nexus.WeightTracker.Api']

stages:
  - stage: deploy_${{ parameters.projectName }}
    jobs:
      - ${{ each dbProject in parameters.dbProjects }}:
        - template: ../jobs/db_deploy_job.yml
          parameters:
            projectName: ${{ replace(dbProject,'.','_') }}
      - template: ../jobs/docker_deploy_job.yml
        parameters:
          projectName: ${{ parameters.projectName }}


          
          
  