parameters:
  - name: projectName
    type: string
    
stages:
  - stage: ${{ replace(parameters.projectName, '.','_') }}_Build
    jobs:
      - template: ../jobs/docker_build_and_push_job.yml
        parameters:
          projectName: ${{ parameters.projectName }}
      - template: ../jobs/db_build_and_publish_jobs.yml
        parameters:
          projectName: ${{ parameters.projectName }}.Database
          
    