parameters:
  - name: projectName
    type: string

stages:
  - stage: ${{ replace(parameters.projectName, '.','_') }}_Build
    jobs:
      - template: ../jobs/db_build_and_publish_job.yml
        parameters:
          projectName: ${{ parameters.projectName }}