parameters:
  - name: solutionName
    type: string
  - name: projectNames
    type: object
    
stages:
  - stage: ${{ replace(parameters.solutionName, '.','_') }}_Build
    variables:
      solutionPath: '$(Build.SourcesDirectory)/${{ parameters.solutionName }}/'
    jobs:
      - ${{ each projectName in parameters.projectNames }}:
        - template: ../jobs/docker_build_and_push_job.yml
          parameters:
            dockerFilePath: ${{ variables.solutionPath }}${{ projectName }}**/Dockerfile
            projectName: ${{ replace(projectName, '.','_' ) }}
    