metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - app.itadams.co.uk
    secretName: webblazor-production-tls
  - hosts:
    - identity.itadams.co.uk
    secretName: identity-api-production-tls
  - hosts:
    - status.itadams.co.uk
    secretName: webstatus-production-tls
   